spring:
  profiles:
    active:  prod,token
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.up.iotbackend.entity
