server:
  port: 8091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/up_prod?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&nullCatalogMeansCurrent=true&useSSl=false
    username: root
    password: Vitesco2022!!!!
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
savePath:
  profilePhotoPath: /Users/anfeng/up/img/ #local resource
  profilePhotoMapper: /upload/img/ #图标的映射路径